- name: Deploy Keycloak custom resource
  k8s:
    definition: "{{ item }}"
    namespace: "{{ k8s_namespace }}"
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
    state: present
  loop:
    - "{{ lookup('template', 'templates/keycloak/keycloak.yaml') | from_yaml_all | list }}"

- name: Deploy custom Keycloak Ingress
  k8s:
    definition: "{{ item }}"
    namespace: "{{ k8s_namespace }}"
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
    state: present
  loop:
    - "{{ lookup('template', 'templates/keycloak/keycloak-ingress.yaml') | from_yaml }}"
