- name: Set keycloak deployment instances to 2
  set_fact:
    keycloak_replicas: 2

- name: Deploy Keycloak custom resource
  k8s:
    definition: "{{ item }}"
    namespace: "{{ k8s_namespace }}"
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
    state: present
  loop:
    - "{{ lookup('template', 'templates/keycloak/deployment/keycloak.yaml') | from_yaml_all | list }}"

- name: Wait for Keylcoak Start-Up
  wait_for:
    timeout: 180