- name: Deploy Keycloak custom resource
  k8s:
    definition: "{{ item }}"
    namespace: "{{ k8s_namespace }}"
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
    state: present
  loop:
<<<<<<< HEAD
    - "{{ lookup('template', 'templates/keycloak/deployment/keycloak.yaml') | from_yaml_all | list }}"
=======
    - "{{ lookup('template', 'templates/keycloak/keycloak.yaml') | from_yaml_all | list }}"
>>>>>>> 70f8f1d (deployment and initial configs)

- name: Deploy custom Keycloak Ingress
  k8s:
    definition: "{{ item }}"
    namespace: "{{ k8s_namespace }}"
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
    state: present
  loop:
<<<<<<< HEAD
    - "{{ lookup('template', 'templates/keycloak/deployment/keycloak-ingress.yaml') | from_yaml }}"
=======
    - "{{ lookup('template', 'templates/keycloak/keycloak-ingress.yaml') | from_yaml }}"
>>>>>>> 70f8f1d (deployment and initial configs)
