---
#file 02_setup_k8s/vars/default.yml

# SSH-Key of user 'acn'
copy_local_key: "{{ lookup('env', 'FUTR_HUB_ACN_SSHKEY_PATH') }}/{{ lookup('env', 'FUTR_HUB_ACN_SSHKEY') }}"
copy_local_pub_key: "{{ lookup('file', lookup('env', 'FUTR_HUB_ACN_SSHKEY_PATH') + '/' + lookup('env', 'FUTR_HUB_ACN_SSHKEY') + '.pub') }}"

# Necessary System packages we need to intall
sys_packages: [ 'curl', 'vim', 'snapd', 'python3', 'python3-pip', 'ufw', 'htop', 'snap']

# Set K8s kubeconfig
proxy_env:
  K8S_AUTH_KUBECONFIG: "/home/acn/.kube/k8s-master_config"
