---
#file 02_setup_k8s/vars/default.yml

# SSH-Key of user 'acn'
copy_local_key: "{{ PLATFORM_SSHKEY_PATH }}/{{ PLATFORM_SSHKEY_NAME }}"
copy_local_pub_key: "{{ lookup('file', lookup('env','HOME') + '/' + PLATFORM_SSHKEY_PATH + '/' + PLATFORM_SSHKEY_NAME  + '.pub') }}"

# Necessary System packages we need to intall
sys_packages: [ 'curl', 'vim', 'snapd', 'python3', 'python3-pip', 'ufw', 'htop', 'snap']

# Set K8s kubeconfig
proxy_env:
  K8S_AUTH_KUBECONFIG: "{{ lookup('env','HOME') }}/.kube/{{ kubeconfig_file }}"

# Namespace
cert_manager_namespace: "cert-manager"

k8s_ingress_class: public