---
- name: Check if local kubeconfig exists
  ansible.builtin.stat:
    path: "~/.kube/{{ inventory_hostname }}_config"
  delegate_to: localhost
  register: result
  become: no

- name: 'Fail if local {{ inventory_hostname }}_config already exists.'
  fail:
    msg: "{{ inventory_hostname }}_config already exists locally"
  when: result.stat.exists

- name: Generate kubeconfig
  shell: "source /etc/profile.d/apps-bin-path.sh && /snap/bin/microk8s config >> {{ inventory_hostname }}_config"
  args:
    executable: /bin/bash
  when: not result.stat.exists

- name: Fetch {{ inventory_hostname }}_config to local system
  fetch:
    src: "{{ inventory_hostname }}_config"
    dest: "~/.kube/"
    flat: yes

- name: Change file ownership, group and permissions of kubeconfig-file
  ansible.builtin.file:
    path: "~/.kube/{{ inventory_hostname }}_config"
    owner: acn
    group: acn
    mode: '0600'
  delegate_to: localhost
  become: no
  when: not result.stat.exists

- name: Create directore /home/acn/.kube on remote system
  ansible.builtin.file:
    path: "/home/acn/.kube"
    state: directory
    owner: acn
    group: acn
    mode: '0755'

- name: Copy kubeconfig to /home/acn/.kube on remote system
  ansible.builtin.copy:
    src: "~/.kube/{{ inventory_hostname }}_config"
    dest: "/home/acn/.kube/{{ inventory_hostname }}_config"
    owner: acn
    group: acn
    mode: '0600'
