---
# file: 03_setup_k8s_platform/vars/default.yml

# ChartMuseum
CM_PORT: 8879
CM_STORAGE: local
CM_STORAGE_LOCAL_ROOTDIR: ~/futr_hub_apps
CM_CONTEXT_PATH: charts

# Helm
HELM_REPO_URL: http://127.0.0.1
HELM_REPO_NAME: futr-hub

# Kubernetes
K8S_KUBECONFIG: "{{ lookup('env', 'HOME') }}/.kube/k8s-master_config"
K8S_CONTEXT: microk8s
K8S_NAMESPACE_GEODATA: geodata
K8S_NAMESPACE_CKAN: ckan
K8S_NAMESPACE_FROST: frost-server
K8S_NAMESPACE_POSTGRES_OPERATOR: op-postgres
K8S_NAMESPACE_MINIO_OPERATOR: op-minio
K8S_NAMESPACE_DATA_MANAGEMENT_OPERATOR: data-management
K8S_NAMESPACE_PUBLIC: public
K8S_NAMESPACE_MONITORING: monitoring-logging
K8S_NAMESPACE_DATAFLOWSTACK: dataflow-stack
K8S_NAMESPACE_CONTEXT_MANAGEMENT_STACK: context-management-stack
K8S_NAMESPACE_IDMSTACK: idm-stack
K8S_INGRESS_CLASS: public

# GitLab-API-URL
GITLAB_API_URL: "https://gitlab.com/api/v4"
