---
# file: 03_setup_k8s_platform/tasks/context_management-stack/install_quantumleap.yml

- name: Read values for Quantum Leap
  ansible.builtin.include_vars:
    file: context_management-stack/quantumleap.yml
    name: quantumleap

- name: Check if Quantumleap secret already exists in the cluster
  community.kubernetes.k8s_info:
    kubeconfig: "{{ k8s_config }}"
    namespace: "{{ k8s_namespace }}"
    context: "{{ k8s_context }}"
    kind: Secret
    name: 'quantumleap-database-secret'
  register: quantumleap_secret

- name: Create random Quantumleap secret if it does not exist
  when: quantumleap_secret.resources | length == 0
  vars:
    ql_new_pass: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters') | b64encode }}"
  k8s:
    state: present
    namespace: '{{ k8s_namespace_name }}'
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: quantumleap-database-secret
      data:
        password: "{{ ql_new_pass }}"

- name: Deploy Quantumleap
  k8s:
    definition: "{{ item }}"
    kubeconfig: '{{ kubeconfig }}'
    namespace: '{{ k8s_namespace_name }}'
    state: present
  loop:
    - "{{ lookup('template', 'templates/fiware/quantumleap.yml') | from_yaml_all | list }}"
