---
# file: 03_setup_k8s_platform/tasks/context_management-stack/install_mongodb.yml

- name: Read MongoDB values
  ansible.builtin.include_vars:
    file: context_management-stack/mongodb.yml
    name: mongodb

- name: Deploy MongoDB v3.6
  community.kubernetes.k8s:
    state: present
    kubeconfig: "{{ k8s_config }}"
    context: "{{ k8s_context }}"
    namespace: "{{ k8s_namespace }}"
    definition: "{{ item }}"
  loop:
    - "{{ lookup('template', 'templates/context_management-stack/mongodb.yml') | from_yaml_all | list }}"
